[project]
name = "classifica-noticia"
version = "0.1.0"
dependencies = [
    "requests",
    "beautifulsoup4",
    "streamlit",
    "pandas",
    "python-dotenv",
    "psycopg2-binary"
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
